name: ci

on:
  pull_request:

env:
  DOCKER_TAG: dev

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - id: lower-repo
        run: |
          echo "IMAGE=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}  # Checkout the PR branch

      - name: Build Docker Image
        run: docker build -t ${{ steps.lower-repo.outputs.repository  }} .

      - name: Validate Docker Image
        run: |
          if [ "$(docker images -q ${{ steps.lower-repo.outputs.repository }} 2> /dev/null)" == "" ]; then
            echo "Docker image build failed!"
            exit 1
          else
            echo "Docker image build successful!"
          fi